name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: sudo apt-get install -y nasm gcc make -qq

      - name: Build
        run: make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: maxos-build-${{ github.sha }}
          path: build/os.img
          if-no-files-found: ignore
